/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, ButtonType, ButtonVariant } from "./components/aw-button/types";
import { Direction, Size } from "./components/icons/types";
export namespace Components {
    interface AwButton {
        /**
          * Define if button takes all width of container or if container is a flex, the button assume flex=1
         */
        "blocked"?: boolean;
        /**
          * Define if buttons is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Define button size
          * @default medium
         */
        "size"?: ButtonSize;
        /**
          * Button type
          * @values button, submit
          * @default button
         */
        "type"?: ButtonType;
        /**
          * Button variant
          * @values primary, danger, warning, outline
          * @default primary
         */
        "variant"?: ButtonVariant;
    }
    interface AwIconArrow {
        "color"?: string;
        "direction"?: Direction;
        "noTransition"?: boolean;
        "size"?: Size;
    }
    interface AwIconSearch {
        "color"?: string;
        "direction"?: Direction;
        "noTransition"?: boolean;
        "size"?: Size;
    }
    interface AwvComponentGroup {
        "title": string;
    }
}
declare global {
    interface HTMLAwButtonElement extends Components.AwButton, HTMLStencilElement {
    }
    var HTMLAwButtonElement: {
        prototype: HTMLAwButtonElement;
        new (): HTMLAwButtonElement;
    };
    interface HTMLAwIconArrowElement extends Components.AwIconArrow, HTMLStencilElement {
    }
    var HTMLAwIconArrowElement: {
        prototype: HTMLAwIconArrowElement;
        new (): HTMLAwIconArrowElement;
    };
    interface HTMLAwIconSearchElement extends Components.AwIconSearch, HTMLStencilElement {
    }
    var HTMLAwIconSearchElement: {
        prototype: HTMLAwIconSearchElement;
        new (): HTMLAwIconSearchElement;
    };
    interface HTMLAwvComponentGroupElement extends Components.AwvComponentGroup, HTMLStencilElement {
    }
    var HTMLAwvComponentGroupElement: {
        prototype: HTMLAwvComponentGroupElement;
        new (): HTMLAwvComponentGroupElement;
    };
    interface HTMLElementTagNameMap {
        "aw-button": HTMLAwButtonElement;
        "aw-icon-arrow": HTMLAwIconArrowElement;
        "aw-icon-search": HTMLAwIconSearchElement;
        "awv-component-group": HTMLAwvComponentGroupElement;
    }
}
declare namespace LocalJSX {
    interface AwButton {
        /**
          * Define if button takes all width of container or if container is a flex, the button assume flex=1
         */
        "blocked"?: boolean;
        /**
          * Define if buttons is disabled
          * @default false
         */
        "disabled"?: boolean;
        "onAwClicked"?: (event: CustomEvent<void>) => void;
        /**
          * Define button size
          * @default medium
         */
        "size"?: ButtonSize;
        /**
          * Button type
          * @values button, submit
          * @default button
         */
        "type"?: ButtonType;
        /**
          * Button variant
          * @values primary, danger, warning, outline
          * @default primary
         */
        "variant"?: ButtonVariant;
    }
    interface AwIconArrow {
        "color"?: string;
        "direction"?: Direction;
        "noTransition"?: boolean;
        "size"?: Size;
    }
    interface AwIconSearch {
        "color"?: string;
        "direction"?: Direction;
        "noTransition"?: boolean;
        "size"?: Size;
    }
    interface AwvComponentGroup {
        "title"?: string;
    }
    interface IntrinsicElements {
        "aw-button": AwButton;
        "aw-icon-arrow": AwIconArrow;
        "aw-icon-search": AwIconSearch;
        "awv-component-group": AwvComponentGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aw-button": LocalJSX.AwButton & JSXBase.HTMLAttributes<HTMLAwButtonElement>;
            "aw-icon-arrow": LocalJSX.AwIconArrow & JSXBase.HTMLAttributes<HTMLAwIconArrowElement>;
            "aw-icon-search": LocalJSX.AwIconSearch & JSXBase.HTMLAttributes<HTMLAwIconSearchElement>;
            "awv-component-group": LocalJSX.AwvComponentGroup & JSXBase.HTMLAttributes<HTMLAwvComponentGroupElement>;
        }
    }
}
